import type { CurrentRevisionAssignment } from './current-revision-runtime';

const CENSUS_CONTRACT_ID = 'PORTFOLIO-R1-A2.1-2026-08-31';

function revision(
  subjectKey: string,
  recordId: `rec_${string}`,
  name: string,
  summary: string,
  thesis: string | null,
  repositoryRefs: string[],
  summaryBasis: string[],
  thesisBasis: string[] = thesis === null ? [] : summaryBasis,
): CurrentRevisionAssignment {
  return {
    subjectKey,
    recordId,
    lifecycle: 'active',
    payload: { schemaVersion: 'knowledge.system/v0', name, summary, thesis },
    temporalBasis: { censusContractId: CENSUS_CONTRACT_ID, repositoryRefs },
    grounding: { summaryBasis, thesisBasis, privateEvidenceMayBePublished: false },
  };
}

export const CURRENT_SYSTEM_REVISION_ASSIGNMENTS: CurrentRevisionAssignment[] = [
  revision(
    'genesis',
    'rec_5eeb93bd8811b6c0fbecf3cc733cbd2e',
    'Genesis',
    'Sovereign agentic web runtime that owns institutional identity, authority, causal history, effect reconciliation and recovery above replaceable physical substrates.',
    'The Web can be treated as an operational environment in which physical browser and OS mechanisms remain substrate while Genesis owns institutional identity, governed authority and causal continuity.',
    ['4LFR3Dv1/Genesis'],
    ['4LFR3Dv1/Genesis:README.md'],
  ),
  revision(
    'brineos',
    'rec_6822adfb4aaf3520816ff305f6b4e572',
    'BrineOS',
    'Bare-metal research system exploring the minimum deterministic substrate required for a persistent AI-native entity to exist directly on a machine.',
    'Cognition may be replaceable while continuity, authority, state, effects, evidence and recovery belong to the machine-owned substrate that sustains the entity.',
    ['4LFR3Dv1/BrineOS'],
    ['4LFR3Dv1/BrineOS:README.md'],
  ),
  revision(
    'wer-esk',
    'rec_4515d2eb7d17e9a876ff890f7b90d6a8',
    'WER-ESK',
    'Local kernel for cartography and exploration of the Internet through bounded Web observations, explicit provenance and deterministic relation frontiers.',
    'The Internet can be explored as an observable relational space without turning the exploration layer into an application ledger or remote authority.',
    ['4LFR3Dv1/wer-esk'],
    ['4LFR3Dv1/wer-esk:README.md'],
  ),
  revision(
    'lisa',
    'rec_286639cfc48e0fac9065fe4e3258a916',
    'Lisa',
    'Digital operational presence that handles business conversations with persistent context, grounded knowledge and bounded operational actions.',
    'A business-facing AI presence should preserve conversational and operational continuity while separating cognition, knowledge retrieval and authorized actions.',
    ['4LFR3Dv1/lisa-web', '4LFR3Dv1/lisa-app', '4LFR3Dv1/lisa-runtime'],
    ['4LFR3Dv1/lisa-runtime:lisa_architecture_v1.md'],
  ),
  revision(
    'factory',
    'rec_1fe061f491894efe1e0b1674448b7501',
    'Factory',
    'External governed production system that turns Coordinator decisions into bounded, independently verified source changes through a persistent host and capability-restricted workers.',
    'Agentic software production should separate coordination, execution authority and independent verification instead of allowing workers to define or accept their own work.',
    ['4LFR3Dv1/brine-factory'],
    ['4LFR3Dv1/brine-factory:README.md'],
  ),
  revision(
    'foundry',
    'rec_66057eae80fabfa4478a600481d755f0',
    'Foundry',
    'Local-priority cockpit for orchestrating software agents with durable state, explicit contracts, evidence, human review and Git-backed work history.',
    'Agentic development becomes operationally tractable when planning, execution, evidence and review are represented as governed state rather than disposable chat sessions.',
    ['SNE-Labs/Foundry', '4LFR3Dv1/FoundryLandingPage'],
    ['SNE-Labs/Foundry:README.md'],
  ),
  revision(
    'agenthub',
    'rec_10d864e055b79f67dce52412083e6763',
    'AgentHub',
    'Independent product for buying digital work executed by specialized agents, with its own public application, job model, delivery flow, data and operation.',
    'Agentic capability can be exposed as finished digital work while keeping customer-facing product state independent from the internal software-production cockpit.',
    ['SNE-Labs/AgentHub'],
    ['SNE-Labs/AgentHub:README.md'],
  ),
  revision(
    'foundry-pay',
    'rec_0e6beb6a5f17831616af328fe8f2afb2',
    'Foundry Pay',
    'Governed payment infrastructure for agent systems and stablecoin applications that separates economic authority from network execution.',
    'An application may request an economic effect without gaining unrestricted signer authority when obligations, authorization, execution, recovery and reconciliation are bound independently.',
    ['4LFR3Dv1/Foundry-Pay'],
    ['4LFR3Dv1/Foundry-Pay:README.md'],
  ),
  revision(
    'foundry-channels',
    'rec_38f6f81328b9ccd007127d1071f8cc02',
    'Foundry Channels',
    'Product and runtime surface for persistent funded stablecoin payment channels, separated from protocol authority and network-specific execution infrastructure.',
    'Consumer channel state should come from durable application state reconciled with authorized protocol reality rather than fabricated UI or inferred execution.',
    ['4LFR3Dv1/Foundry-Channels'],
    ['4LFR3Dv1/Foundry-Channels:README.md'],
  ),
  revision(
    'solana-agent',
    'rec_43dd086ef220193d441943461e8863f0',
    'Solana-Agent',
    'Governed execution, recovery and evidence infrastructure for Solana operations proposed by applications or AI agents.',
    'Agents may propose Solana work without receiving unrestricted signer authority when policy, exact authorization, execution, journaling, recovery and evidence remain separate responsibilities.',
    ['4LFR3Dv1/Solana-Agent'],
    ['4LFR3Dv1/Solana-Agent:README.md'],
  ),
  revision(
    'sne-fde',
    'rec_6bd4d56023990c25879daecf2ff34b55',
    'SNE-FDE',
    'Institutional and executable field boundary of SNE Labs, connecting computing thesis, computational treasury, field contracts, evidence and an external problem-intake surface.',
    'SNE Labs should expose computing through reality, problems, work and evidence while preserving a separate institutional chain from company to treasury, field and evidence.',
    ['SNE-Labs/SNE-FDE', 'SNE-Labs/Public-Surface'],
    ['SNE-Labs/SNE-FDE:README.md'],
  ),
  revision(
    'github-flow',
    'rec_0db35eb308dd8da06948dcde9666a6df',
    'GitHub Flow',
    'Operational workspace over GitHub reality that relates repository state, reconstructs frontiers and presents an automatic view of ongoing work.',
    'GitHub remains source of truth and governance while a separate workspace can reconstruct and present its operational state without replacing that authority.',
    ['4LFR3Dv1/GitHub-Flow'],
    ['4LFR3Dv1/GitHub-Flow:README.md'],
  ),
  revision(
    'sne-os',
    'rec_499f928363217da10f93cd54aead0101',
    'SNE-OS',
    'USDT-first self-custodial operational workspace combining market context, on-chain balance, multichain movement, operational identity, access keys, encrypted secrets and reference surfaces.',
    'A sovereign digital-dollar account can use USDT as its base balance while unifying context, identity, access and execution without giving up self-custody.',
    ['SNE-Labs/SNE-OS'],
    ['SNE-Labs/SNE-OS:README.md', 'SNE-Labs/SNE-OS:src/app/navigation.ts'],
    ['SNE-Labs/SNE-OS:src/app/navigation.ts'],
  ),
  revision(
    'sne-radar',
    'rec_553b9088a5b22a51a44679f582de47f5',
    'SNE Radar',
    'Market-intelligence and signal-analysis system in the SNE lineage, with market data, signal surfaces and authenticated analysis paths across its current and historical repository realizations.',
    null,
    ['4LFR3Dv1/SNE-RADAR-v1.0', '4LFR3Dv1/SNE-RADAR', '4LFR3Dv1/SNE-V1.0-CLOSED-BETA-', 'SNE-Labs/SNE-Radar', 'SNE-Labs/SNE-Radar-Standalone', 'SNE-Labs/ADMIN-API'],
    ['SNE-Labs/SNE-Radar:backend-v2/services/sne-web/app/radar_api.py', 'R1-PRE:GCG-016'],
  ),
  revision(
    'sne-trading',
    'rec_b1afa6a6409eff3f0c4d55f88b2112b2',
    'SNE Trading',
    'Independent research, replay, risk and execution plane for SNE market intelligence, designed to evaluate historical signal behavior before any controlled execution.',
    'The system being judged should not control the tribunal that judges it; signal generation, historical evaluation, risk authority and execution must remain separable.',
    ['4LFR3Dv1/SNE-Trading'],
    ['4LFR3Dv1/SNE-Trading:README.md'],
  ),
  revision(
    'brine',
    'rec_5c9f2ece90fb6528b9b317a5181d5336',
    'Brine',
    'Local-first agent runtime for persistent computer work that owns identity, durable state, sessions, memory, authority, tool effects, receipts and recovery around replaceable cognition.',
    'Agent sovereignty comes from owning authoritative runtime state and effect boundaries rather than from binding identity to a particular model, provider or harness.',
    ['4LFR3Dv1/BrineT'],
    ['4LFR3Dv1/BrineT:README.md'],
  ),
  revision(
    'personal-identity-runtime',
    'rec_10610fee4c64c6463ccbb745deaf1a92',
    'Personal Identity Runtime',
    'Local-first Windows runtime for a persistent digital identity with durable observation, reconstructible projections, episodic memory, bounded cognition and evidence-gated manifestations.',
    'A persistent digital identity can outlive any one interface by keeping runtime continuity and durable state independent from its desktop shell.',
    ['4LFR3Dv1/identity-runtime'],
    ['4LFR3Dv1/identity-runtime:README.md'],
  ),
  revision(
    'vira',
    'rec_c844725e35cf61830221efc597612017',
    'VIRA',
    'Live football multiplayer experience that turns authoritative match observations into synchronized challenges, private answers, shared resolution, ranking and verifiable replay.',
    'A live match can become a synchronized social game when one authoritative event stream controls challenge timing and resolution for every participant.',
    ['4LFR3Dv1/VIRA-'],
    ['4LFR3Dv1/VIRA-:README.md'],
  ),
  revision(
    'xs-wallet',
    'rec_724d518ee338e32eb06e79077ad01f3d',
    'XS Wallet / Domini',
    'Pre-beta self-custody desktop wallet for BTC, Liquid and Lightning with modular frontend, Electron, API bridge and Go core, including wallet and swap flows.',
    'Critical wallet operations should remain self-custodial and IPC-first, with encrypted local key material and explicit session boundaries across the desktop stack.',
    ['4LFR3Dv1/XSWallet'],
    ['4LFR3Dv1/XSWallet:README.md'],
  ),
  revision(
    'ordm',
    'rec_f941765df0d17315570234ddb6df2c24',
    'ORDM',
    'Legacy blockchain research family exploring offline or local block production, hybrid consensus, peer coordination, persistence and wallet-security controls.',
    'Blockchain experiments can separate local or offline production from later network reconciliation, but the historical PoC and testnet realizations remain a research lineage rather than a production network.',
    ['4LFR3Dv1/ordm', '4LFR3Dv1/ORDM-TESTNET-v.01', '4LFR3Dv1/ordm-testnet'],
    ['4LFR3Dv1/ordm:README.md', '4LFR3Dv1/ordm-testnet:README.md'],
  ),
  revision(
    'sne-vault',
    'rec_358fbaec4b74b7f1739ea5943c4a4ca0',
    'SNE Vault',
    'Historical SNE system surface for verifiable edge execution, encrypted storage, on-chain licensing and hardware-rooted operational concepts.',
    null,
    ['SNE-Labs/SNE-Labs'],
    ['SNE-Labs/SNE-Labs:README.md'],
  ),
  revision(
    'sne-scroll-pass',
    'rec_eb671d4728bb44327b1a0b832006f320',
    'SNE Scroll Pass',
    'Privacy-first interface for inspecting and interacting with the Scroll ecosystem, including balances, gas, watchlists and wallet-oriented views.',
    'Blockchain control surfaces can reduce noise and tracking by exposing only requested account and network information through a focused interface.',
    ['SNE-Labs/SNE-Scroll-Passport'],
    ['SNE-Labs/SNE-Scroll-Passport:README.md'],
  ),
  revision(
    'sne-observatorio',
    'rec_c2af8a986e38518d716f397320072368',
    'SNE Observatório',
    'Historical market-research system that represented price behavior through a proprietary visual language of fields, resonances, flows and temporal exploration.',
    'Market analysis can be expressed as a visual language of interacting forces rather than only as conventional indicator and signal tables.',
    ['4LFR3Dv1/OBSERVATORIO-SNE'],
    ['4LFR3Dv1/OBSERVATORIO-SNE:README_SNE_v2.md'],
  ),
  revision(
    'viewcounter',
    'rec_757fe2f771ef44acc68af55ce9313c95',
    'ViewCounter',
    'Experimental social-metrics dashboard that connects authorized YouTube and TikTok accounts, snapshots total views, aggregates growth and streams updated projections.',
    'Cross-platform social metrics become comparable when provider observations are normalized into one durable history while failures preserve the last valid measurement instead of fabricating data.',
    ['4LFR3Dv1/ViewCounter'],
    ['4LFR3Dv1/ViewCounter:README.md'],
  ),
  revision(
    'edital-sales',
    'rec_e8947ad40f9a202dc9413a1bb91199f1',
    'Edital Sales',
    'Application for public-notice discovery, opportunity CRM, artist and project records, source ingestion and assisted analysis through a React frontend and Python backend.',
    null,
    ['4LFR3Dv1/EditalSales'],
    ['4LFR3Dv1/EditalSales:README.md'],
  ),
  revision(
    'estampai',
    'rec_b9dc85a2002a434fdb540b53496c99f2',
    'EstampAI',
    'Experimental conversational design system in which users describe a print, receive generated visual patterns and inspect or export the resulting PNG assets.',
    null,
    ['4LFR3Dv1/estampai'],
    ['4LFR3Dv1/estampai:README.md'],
  ),
  revision(
    'vlbet',
    'rec_ad5db27acd07f0934b47ae313e9e812f',
    'VLBet',
    'Experimental sports value engine combining multi-provider odds ingestion, Elo and Poisson probability models, Kelly sizing and signal delivery.',
    'A value-betting signal should emerge from an explicit comparison between estimated probability and market price, with sizing separated into a formal risk rule.',
    ['4LFR3Dv1/vlbet'],
    ['4LFR3Dv1/vlbet:README.md'],
  ),
];

export const CURRENT_SYSTEM_REVISION_DEFERRED = [
  {
    subjectKey: 'transactional-support-bot',
    recordId: 'rec_c5a75fd5ecae0565aaa0c96f0ad53227' as const,
    reason: 'no-current-repository-successor-and-no-new-current-semantic-evidence',
  },
];
